version: '3.8'

services:
  flask_api:
    build: ./python_api
    container_name: python_api
    ports:
      - "5000:5000"
    volumes:
      - ./python_api:/app        
      - ./python_api/.env:/app/.env 
    environment:
      - FLASK_ENV=development
    depends_on:
      - mysql_db 
    command: "python /app/app.py"  
    networks:
      - app-networks

  mysql_db:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
    ports:
      - "5555:3306"  
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d 
    networks:
      - app-networks

  node_api:
    build:
      context: ./node_api
    container_name: node_api
    ports:
      - "3000:3000"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
